apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: nodejs-rest-http
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/midawson-tenant/nodejs-rest-http/nodejs-rest-http@sha256:dd009132091c714c8d0034a91c67300fccc2ef242a7f156bfc19e924ab6d8d0d
        name: my-nodejs
        resources: {}
status: {}
