apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: nodejs-rest-http
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/midawson-tenant/nodejs-rest-http/nodejs-rest-http@sha256:0907ad3109729d8680abfd895625b1169d64491c3023a7c26e193ab3145b7251
        name: my-nodejs
        resources: {}
status: {}
